library(readxl)
library(plyr)

table1 <- read_excel("C:/Users/Brendan.Hellweg/Desktop/Invoice Payments Folder/November 2019 Table.xlsx")
payments <-table1[table1$`Days Since Creation`>30,]
id <- payments$`Execution ID`
location <- payments$Location
age <- payments$`Status Age (days)`
creation <- payments$`Days Since Creation`
date <- payments$`Creation Date`
type <- payments$`Document Type`
vendor <- payments$`Vendor Name`

payments$agency <- location
agency <- payments$agency
payments <- payments[,c(1,17,2,3,4,5,6,7,8,9,11,13,14,15)]
payments$agency <- as.character(payments$agency)


##Giving better names to Agency column
payments$agency <- mapvalues(payments$agency, from=c("AUDITS",
                                                     "BAPS-OPER",
                                                     "BAPS",
                                                     "BBMR",
                                                     "BBMR-Budgets",
                                                     "BCFD-Fire",
                                                     "BCFD",
                                                     "BCIT",
                                                     "MOIT",
                                                     "BCRP",
                                                     "BCRP Operations2",
                                                     "BCRP Operations1",
                                                     "BCRP Capital",
                                                     "NA",
                                                     "blank",
                                                     "N/A",
                                                     "CTCIR-Circuit Court for Balto City",
                                                     "CTCIR",
                                                     "Circuit Court",
                                                     "City Council-President Office",
                                                     "City Council",
                                                     "City Council-District 1",
                                                     "City Council-District 2",
                                                     "City Council-District 3",
                                                     "City Council-District 4",
                                                     "City Council-District 5",
                                                     "City Council-District 6",
                                                     "City Council-District 7",
                                                     "City Council-District 8",
                                                     "City Council-District 9",
                                                     "City Council-District 10",
                                                     "City Council-District 11",
                                                     "City Council-District 12",
                                                     "City Council-District 13",
                                                     "City Council-District 14",
                                                     "City Council-Council Services",
                                                     "COMPT",
                                                     "COMPT-Municipal Telephone Exchange",
                                                     "COMPT-Municipal Post Office",
                                                     "COMPT-Exec Office",
                                                     "Comptrollers Office",
                                                     "CONV-Convention Center",
                                                     "CONV",
                                                     "Convention Center",
                                                     "DHCD-Blight Elimination- Capital",
                                                     "DHCD - CitiBuy - Operating",
                                                     "DHCD",
                                                     "DHCD - CitiBuy - Capital",
                                                     "DHCD-Operating- Rehab",
                                                     "DHCD-Hotel Bills",
                                                     "DHCD- Community Services",
                                                     "DHCD-Lead Paint Abatement",
                                                     "DHCD-Housing Code Enforcement-Legal",
                                                     "DHCD-Admin-Capital",
                                                     "DHCD-Capital- Rehab",
                                                     "DHCD-Blight Elimination- Operating",
                                                     "DHCD-Capital- Law",
                                                     "DHCD-Office of Home Energy-Weatherization",
                                                     "DHCD-Dawson Center",
                                                     "DHCD-Operating- Project Finance",
                                                     "DHCD-Capital- Home Ownership",
                                                     "DHCD-Child Care",
                                                     "DHCD-Blight Elimination-Karen Gilmore remove",
                                                     "DHCD-Baltimore Development Corp",
                                                     "DOT",
                                                     "DOT-697-Traffic Safety",
                                                     "DOT - 696 - Street Cuts",
                                                     "DOT- 681 - Administration",
                                                     "DOT- 684 - Traffic Management and Safety",
                                                     "DOT- 689 - Vehicle Impounding and Disposal",
                                                     "DOT- 500 - Street and Park Lighting",
                                                     "DOT- 694 - Survey Control",
                                                     "DOT- Admin-Capital",
                                                     "DOT- Tech - Capital",
                                                     "DOT- 683 - Street Management",
                                                     "DOT- 692 - Bridge and Culvert Management",
                                                     "DOT- 548 - Conduits",
                                                     "DPW-Admin-Pr.190 Contract Admin Act.008",
                                                     "DPW-Admin-Pr.190 Board&Commisions Act.006",
                                                     "DPW",
                                                     "DPW-Asset Mgmt",
                                                     "DPW-Admin",
                                                     "DPW-W&WW-Rev Measuremnt & Billing Div Admin",
                                                     "DPW-Energy",
                                                     "DPW-Environmental Police",
                                                     "DPW-W&WW - Environmental Services",
                                                     "DPW-W&WW-Engineering & Const.",
                                                     "DPW-OCAL",
                                                     "DPW-W&WW-Maint Division",
                                                     "DPW-SW-Solid Waste",
                                                     "DPW-W&WW-WW Facilities ALL",
                                                     "DPW-W&WW-Envrmnt Serv Div Pollution Control",
                                                     "DPW-W&WW-Envrmnt Laboratory (Patapsco)",
                                                     "DPW-W&WW-Envrmnt Water Treatment(Ashburton)",
                                                     "DPW-W&WW-WW Facilities Div Patapsco Op",
                                                     "DPW-W&WW-OCAL",
                                                     "DPW Capital",
                                                     "Elections",
                                                     "Environmental Control Board",
                                                     "ERS-Empl Retirement System",
                                                     "Finance",
                                                     "ORM-Office of Risk Management",
                                                     "Treasury Management",
                                                     "Finance-Collections Delinquent Accts",
                                                     "Finance-Collections",
                                                     "Dept of Gen Serv",
                                                     "DGS - CitiBuy",
                                                     "General Services-Construction Management",
                                                     "General Services",
                                                     "General Services-Building Maint",
                                                     "General Services-Engineering",
                                                     "General Services-Fleet Mgmt",
                                                     "General Services-Fiscal",
                                                     "DGS--Fiscal",
                                                     "Health",
                                                     "Health-Admin-Adm Srvs",
                                                     "Health-Admin-FISCAL",
                                                     "Health-Envr-Environment Health",
                                                     "Health-Clinical Services-ClinicsDru/East",
                                                     "Health-Youth&Fam-Dating Matters",
                                                     "Health-Youth&Fam-School Health",
                                                     "Health-Admin-CARE-Community Services",
                                                     "Health-Youth&Fam-WIC Program",
                                                     "Health-Chronic Disease-Cig Restitution",
                                                     "Health-Youth&Fam-MAPC",
                                                     "Health-Chronic Disease-Prevention",
                                                     "Health-Youth&Fam-Early Head Start",
                                                     "Health-Youth&Fam-Safe Streets",
                                                     "Health-Youth&Fam-M & I",
                                                     "Health-Youth&Fam-Infants&Toddlers",
                                                     "Health-Clinical Services-STD",
                                                     "Health-Youth&Fam-MCH Admin",
                                                     "Health-OPHPR",
                                                     "Health-Clinical Services-Oral Health",
                                                     "Health-Hlthy Homes-Outreach",
                                                     "Health-Clinical Services-Immunization",
                                                     "Health-Youth&Fam-RSVP",
                                                     "Health-Chronic Disease-Health Disparities",
                                                     "Health-Admin-CARE-Advocacy",
                                                     "Health-Youth&Fam-SCP",
                                                     "HR-Admin",
                                                     "HR",
                                                     "HR-Employee Benefits",
                                                     "LC-Labor Comm",
                                                     "Labor Comm",
                                                     "LAW",
                                                     "Law-2",
                                                     "LIBR-Enoch Pratt Purchases",
                                                     "LIBRARY",
                                                     "LIBR-Books Purchases",
                                                     "LLC-Liquor License Board",
                                                     "Liquor Board",
                                                     "MO-Mayor's Office",
                                                     "Mayor's Office",
                                                     "MO-Minority/Women-Owned  Business",
                                                     "MO-Cable&Comm",
                                                     "MO-Cable&Comm-Admin",
                                                     "MO-on Criminal Justice",
                                                     "MOCJ",
                                                     "MOED",
                                                     "MOED-Procurement",
                                                     "MOED-Non Procurement",
                                                     "MOED-Contracts",
                                                     "MO-Government Relations",
                                                     "MOHS - Headstart Program",
                                                     "MOHS - Community Action Partner",
                                                     "MOHS - Homeless Services",
                                                     "MOHS - Mayor's Office of Human Services",
                                                     "MOHS",
                                                     "Office of Civil Rights & Wage Commission",
                                                     "OIG-Inspector General",
                                                     "CTORP-Orphan's Court",
                                                     "CTORP",
                                                     "Orphan's Court",
                                                     "Parking Authority",
                                                     "Planning Department",
                                                     "Police",
                                                     "Police-Operating",
                                                     "Police-Grants",
                                                     "Purchasing-Admin",
                                                     "Purchasing-Print Shop",
                                                     "Purchasing",
                                                     "Sheriff's Office",
                                                     "States Attorney Office",
                                                     "ZONE"
),
##List of new cleaned names
                               to=c("AUDITS",
                                    "BAPS",
                                    "BAPS",
                                    "BBMR",
                                    "BBMR",
                                    "BCFD",
                                    "BCFD",
                                    "BCIT",
                                    "BCIT",
                                    "BCRP",
                                    "BCRP",
                                    "BCRP",
                                    "BCRP",
                                    "blank",
                                    "blank",
                                    "blank",
                                    "Circuit Court",
                                    "Circuit Court",
                                    "Circuit Court",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "City Council",
                                    "Comptrollers Office",
                                    "Comptrollers Office",
                                    "Comptrollers Office",
                                    "Comptrollers Office",
                                    "Comptrollers Office",
                                    "Convention Center",
                                    "Convention Center",
                                    "Convention Center",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DHCD",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DOT",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "DPW",
                                    "Elections",
                                    "Environmental Control Board",
                                    "ERS-Empl Retirement System",
                                    "Finance",
                                    "Finance",
                                    "Finance",
                                    "Finance",
                                    "Finance",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "General Services",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "Health",
                                    "HR",
                                    "HR",
                                    "HR",
                                    "Labor Comm",
                                    "Labor Comm",
                                    "Law",
                                    "Law",
                                    "Library",
                                    "Library",
                                    "Library",
                                    "Liquor Board",
                                    "Liquor Board",
                                    "Mayor's Office",
                                    "Mayor's Office",
                                    "Mayor's Office",
                                    "MO-Cable&Comm",
                                    "MO-Cable&Comm",
                                    "MOCJ",
                                    "MOCJ",
                                    "MOED",
                                    "MOED",
                                    "MOED",
                                    "MOED",
                                    "MO-Government Relations",
                                    "MOHS",
                                    "MOHS",
                                    "MOHS",
                                    "MOHS",
                                    "MOHS",
                                    "Office of Civil Rights & Wage Commission",
                                    "OIG-Inspector General",
                                    "Orphan's Court",
                                    "Orphan's Court",
                                    "Orphan's Court",
                                    "Parking Authority",
                                    "Planning Department",
                                    "Police",
                                    "Police",
                                    "Police",
                                    "Purchasing",
                                    "Purchasing",
                                    "Purchasing",
                                    "Sheriff's Office",
                                    "States Attorney Office",
                                    "ZONE"

                              ))

write.csv(payments,"C:/Users/Brendan.Hellweg/Desktop/Invoice Payments Folder/CleanNov.csv")

